### ISSUE TITLE
Energy Dashboard

### ISSUE THREAD

**Issue by a-waider** [SebastianWallat/SolarWattHassio#2]
Hi there, 

nice work with this integration :)

Is it possible to use this integration to provide data to the [energy dashboard](https://demo.home-assistant.io/#/energy)?

**Comment by SebastianWallat** [comment]
Yes this is possible, but you need to add some custom sensors to convert the power values to energy.
This is possible using this template sensor [Energy Template](https://www.home-assistant.io/integrations/integration/#energy)
I added my sensors from the configuration.yaml below:

```yaml
sensor:
  - platform: integration
    source: sensor.energymanager_power_consumed_from_grid
    name: energy_from_grid
    unit_prefix: k
    round: 2
    
  - platform: integration
    source: sensor.energymanager_power_export_to_grid
    name: energy_to_grid
    unit_prefix: k
    round: 2
    
  - platform: integration
    source: sensor.energymanager_power_consumed
    name: energy_consumed
    unit_prefix: k
    round: 2
    
  - platform: integration
    source: sensor.energymanager_pv_power
    name: energy_produced_pv
    unit_prefix: k
    round: 2
```

After adding these it can take some time for them to show up in the energy config (i think it needs to collect some values before they show up)

**Comment by a-waider** [comment]
Thanks!
I added it just now and will test it tomorrow.

**Comment by a-waider** [comment]
So I added the sensors for the myreserve battery with the following `coniguration.yaml`:
```
sensor:
  - platform: integration
    source: sensor.energymanager_power_consumed_from_grid
    name: energy_from_grid
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.energymanager_power_export_to_grid
    name: energy_to_grid
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.energymanager_power_consumed
    name: energy_consumed
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.energymanager_pv_power
    name: energy_produced_pv
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.energymanager_myreserve_power_in_from_producers
    name: energy_battery_from_producers
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.energymanager_myreserve_power_self_supplied
    name: energy_battery_supply
    unit_prefix: k
    round: 2
```

But I can only see the following sensors in my energy dashboard:
- energy_battery_supply
- energy_produced_pv
- energy_from_grid
- energy_consumed

I also got following warnings in my homeassistant logs:
```
2021-09-07 11:09:24 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.energy_to_grid (kWh) does not match the unit of already compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None
2021-09-07 11:09:24 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.energy_battery_from_producers (kWh) does not match the unit of already compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None
```

Do you know how to delete the long term statistics of `energy_battery_from_producers` and `energy_to_grid`?
